add VoidType ConsoleMode
OakLoaf/VoidWarp pull request #1
Opened 2024-12-04 03:12 UTC by AllanGame

This pull request adds a new VoidModeType called ConsoleMode and modifies the behaviour of CommandMode.

Now ConsoleMode replaces the old behaviour of CommandMode running commands from console, and CommandMode now runs commands as player. 

This also adds a few more examples to the default config.

Already tested on a 1.21.1 server

2024-12-04 03:45 UTC, AllanGame commented
I also encountered a few problems with some of the dependencies of this project.
- https://github.com/nulli0n/NexEngine-spigot/ is now outdated, it should be migrated to https://github.com/nulli0n/nightcore-spigot
-  com.github.CodingAir:CodingAPI is only accesible by version 1.90
- A lot of dependencies seem outdated

Should I open an issue to manage dependencies better? Maybe use [rennovate bot](https://github.com/apps/renovate)?

2024-12-04 09:09 UTC, OakLoaf commented
I appreciate the pull request, as this breaks backwards compatibility it's not really something I'd be willing to merge. I would be ok with a new PLAYER_COMMAND type instead, which would add the missing functionality.

As for dependencies I'll setup dependabot and workflows for this repo

2024-12-05 00:32 UTC, AllanGame commented
Oh, I agree, I'll try to get it done by tomorrow

2024-12-05 18:33 UTC, OakLoaf requested changes
Looks good! Just some formatting preferences :))

2024-12-05 18:33 UTC, OakLoaf commented on src/main/java/me/dave/voidwarp/mode/CommandMode.java
> +                )
Could this be reverted?

2024-12-05 18:33 UTC, OakLoaf commented on src/main/java/me/dave/voidwarp/mode/PlayerCommandMode.java
> +          )
Could this be set in the same format as the CommandMode?

2024-12-05 18:33 UTC, OakLoaf commented on src/main/resources/config.yml
> +  warps: [ ]
```suggestion
  warps: []
```

2024-12-05 18:33 UTC, OakLoaf commented on src/main/resources/config.yml
> +  commands: [ "island go" ]
```suggestion
  commands:
  - "island go"
```

2024-12-05 18:33 UTC, OakLoaf commented on src/main/resources/config.yml
> +  ]
```suggestion
  commands:
  - "mv tp %player% world"
  - "eco give %player% 1000"
```

2024-12-05 18:33 UTC, OakLoaf commented on src/main/resources/config.yml
> +  message: "<grey>Teleported to <yellow>your island</yellow>."
MiniMessage doesn't work on spigot servers so legacy formats in default configs are preferred :)
```suggestion
  message: "&7Teleported to &eyour island&7."
```

2024-12-05 20:41 UTC, AllanGame commented
Alright! I'll make the changes right now

2024-12-05 20:46 UTC, OakLoaf approved these changes

2024-12-05 20:46 UTC, OakLoaf commented
Thank you for the PR, I'm really quite busy at the moment so I'm going to hold off on merging but this is good to use :)

2025-09-24 19:18 UTC, closed without merging

2025-09-24 19:18 UTC, OakLoaf commented
Thank you for the PR, it will be uploaded in the next release :)